#!/bin/bash
DIR="$( dirname "${BASH_SOURCE[0]}" )"
OSNAME="$( uname -s | sed -e 's/[-_].*//g' | tr A-Z a-z )"


if [ "$OSNAME" == "linux" ]; then
	sudo su postgres -c "psql < $DIR/drop-db.sql"
fi

if [ "$OSNAME" == "darwin" ]; then
	psql -U postgres < $DIR/drop-db.sql
fi