#!/bin/bash
SERVO="servo.so"

if [ -n $PREFIX]; then
	PREFIX="/usr/local/servo"
fi

mkdir -p $PREFIX/bin
mkdir -p $PREFIX/lib
mkdir -p $PREFIX/conf
mkdir -p $PREFIX/tools
mkdir -p $PREFIX/cert

install -m 555 $SERVO $PREFIX/lib
install -m 555 ./tools/* $PREFIX/tools/

install -m 644 dh2048.pem $PREFIX/cert/dh2048.pem
install -m 644 cert/server.crt $PREFIX/cert/server.crt
install -m 644 cert/server.key $PREFIX/cert/server.key
install -m 644 conf/kore.conf $PREFIX/conf/kore.conf
install -m 644 config.default $PREFIX/conf/servo.conf
